


{
   "email":"mukesh@gmail.com",
   "password":"pass"
}
###

#########access token #######
POST http://localhost:4001/al/login
Content-Type: application/json

{
 
    "email": "suraj@gmail.com",
    "password": "123suraj"

}
###
DELETE http://localhost:4001/al/logout




###
POST http://localhost:4001/al/login
Content-Type: application/json

{
   "email":"mukesh@gmail.com",
   "password":"pass"
}


###
GET http://localhost:4001/a/posts


####
POST http://localhost:4001/note/writter
Content-Type: application/json

{
    "topic":"fasdfdsdsdsadsd",
    "subject":"tefdf6sdsd5",
    "written":"this is testing 2"
    
}



###
GET http://localhost:4001/note/allSaved
 
 