


POST http://localhost:3001/al/login
Content-Type: application/json

{
 
    "email": "suraj@gmail.com",
    "password": "123suraj"

}



###
POST http://localhost:3001/al/login
Content-Type: application/json

{
   "email":"mukesh@gmail.com",
   "password":"pass"
}


###
GET http://localhost:3001/a/posts


####
POST http://localhost:3001/note/writter
Content-Type: application/json

{
    "topic":"topic33",
    "subject":"test67",
    "written":"oo lllll la"
    
}



###
GET http://localhost:3001/note/allSaved
Content-Type: application/json

{
   "author":"mukesh@gmail.com"
}